version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: tarefas_mongo
    ports:
      - "27017:27017"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: tarefas
